const Map<String, String> translationsIDID = {
  'Daftar Pemesanan': 'Daftar Pemesanan',
  'Terjadi kesalahan saat memuat pesanan!':
      'Terjadi kesalahan saat memuat pesanan!',
  'Terjadi kesalahan saat memuat destinasi!':
      'Terjadi kesalahan saat memuat destinasi!',
  'Gratis': 'Gratis',
  'Tertunda': 'Tertunda',
  'Sukses': 'Sukses',
  'Dibatalkan': 'Dibatalkan',
  'Konfirmasi': 'Konfirmasi',
  'Apakah anda ingin membatalkan pemesanan?':
      'Apakah anda ingin membatalkan pemesanan?',
  'Ya': 'Ya',
  'Tidak': 'Tidak',
  'Tunggu sebentar...': 'Tunggu sebentar...',
  'Apakah anda ingin membayar pemesanan?':
      'Apakah anda ingin membayar pemesanan?',
  'Data Pemesanan': 'Data Pemesanan',
  'Nama': 'Nama',
  'Nomor Telpon': 'Nomor Telpon',
  'Tanggal': 'Tanggal',
  'Waktu': 'Waktu',
  'Jumlah Orang': 'Jumlah Orang',
  'Total Harga': 'Total Harga',
  'Batalkan': 'Batalkan',
  'Bayar Sekarang': 'Bayar Sekarang',
  'Konfirmasi Pemesanan': 'Konfirmasi Pemesanan',
  'Detail Informasi': 'Detail Informasi',
  'Selanjutnya': 'Selanjutnya',
  'Buat Pesanan': 'Buat Pesanan',
  'Rubah Data': 'Rubah Data',
  'Harga': 'Harga',
  'Booking maks. h-1': 'Booking maks. h-1',
  'Tanggal*': 'Tanggal*',
  'Nama Lengkap*': 'Nama Lengkap*',
  'Masukkan Nama Lengkap': 'Masukkan Nama Lengkap',
  'Nama lengkap tidak boleh kosong!': 'Nama lengkap tidak boleh kosong!',
  'Nomor Telpon*': 'Nomor Telpon*',
  'Masukkan Nomor Telpon': 'Masukkan Nomor Telpon',
  'Nomor telpon tidak boleh kosong!': 'Nomor telpon tidak boleh kosong!',
  'Jumlah Orang*': 'Jumlah Orang*',
  'Catatan': 'Catatan',
  'Masukkan Catatan': 'Masukkan Catatan',
  'Catatan tidak boleh kosong!': 'Catatan tidak boleh kosong!',
  'Waktu*': 'Waktu*',
  'Memuat...': 'Memuat...',
  'Cari destinasi...': 'Cari destinasi...',
  'Destinasi tidak ada!': 'Destinasi tidak ada!',
  'Terjadi kesalahan saat memuat detail destinasi!':
      'Terjadi kesalahan saat memuat detail destinasi!',
  'Berhasil menyimpan destinasi!': 'Berhasil menyimpan destinasi!',
  'Yuk cari destinasi lainnya.': 'Yuk cari destinasi lainnya.',
  'Gagal!': 'Gagal!',
  'Terjadi masalah dengan server, coba lagi nanti.':
      'Terjadi masalah dengan server, coba lagi nanti.',
  'Berhasil menghapus destinasi!': 'Berhasil menghapus destinasi!',
  'Pesan': 'Pesan',
  'Deskripsi': 'Deskripsi',
  'Lokasi': 'Lokasi',
  'Buka di maps >': 'Buka di maps >',
  'Profil': 'Profil',
  'Pengaturan Akun': 'Pengaturan Akun',
  'Informasi Pribadi': 'Informasi Pribadi',
  'Bookmark': 'Bookmark',
  'Ubah Bahasa': 'Ubah Bahasa',
  'Keluar': 'Keluar',
  'Lainnya': 'Lainnya',
  'Privasi & Kebijakan': 'Privasi & Kebijakan',
  'Informasi Perangkat': 'Informasi Perangkat',
  'Versi Perangkat': 'Versi Perangkat',
  'Terjadi kesalahan saat memuat bookmark!':
      'Terjadi kesalahan saat memuat bookmark!',
  'Tampilan Web Dalam Bingkai': 'Tampilan Web Dalam Bingkai',
  'Apakah anda ingin menyimpan perubahan?':
      'Apakah anda ingin menyimpan perubahan?',
  'Berhasil!': 'Berhasil!',
  'Profil pengguna sudah tersimpan.': 'Profil pengguna sudah tersimpan.',
  'Edit': 'Edit',
  'Email': 'Email',
  'Nama Pengguna': 'Nama Pengguna',
  'Nama pengguna tidak boleh kosong!': 'Nama pengguna tidak boleh kosong!',
  'Alamat': 'Alamat',
  'Ganti Foto Profil': 'Ganti Foto Profil',
  'Perhatian!': 'Perhatian!',
  'Email dan password salah.': 'Email dan password salah.',
  'Error, coba lagi nanti.': 'Error, coba lagi nanti.',
  'Oke': 'Oke',
  'Gagal, coba lagi nanti.': 'Gagal, coba lagi nanti.',
  'Petualanganmu Dimulai di Sini!': 'Petualanganmu Dimulai di Sini!',
  'Lupa password?': 'Lupa password?',
  'Masuk': 'Masuk',
  'Daftar dengan ': 'Daftar dengan ',
  'atau': 'atau',
  'Alamat Email': 'Alamat Email',
  'Alamat email tidak boleh kosong!': 'Alamat email tidak boleh kosong!',
  'Kata Sandi': 'Kata Sandi',
  'Kata sandi tidak boleh kosong!': 'Kata sandi tidak boleh kosong!',
  'Belum punya akun?': 'Belum punya akun?',
  'Daftar': 'Daftar',
  'Siapkan akun Anda': 'Siapkan akun Anda',
  'Silahkan mengisi semua informasi yang dibutuhkan untuk membuat akun baru':
      'Silahkan mengisi semua informasi yang dibutuhkan untuk membuat akun baru',
  'Setuju dengan ': 'Setuju dengan ',
  'ketentuan penggunaan ': 'ketentuan penggunaan ',
  'dan ': 'dan ',
  'kebijakan privasi': 'kebijakan privasi',
  'Buat Akun': 'Buat Akun',
  'Konfirmasi Ulang Kata Sandi': 'Konfirmasi Ulang Kata Sandi',
  'Konfirmasi Password tidak boleh kosong!':
      'Konfirmasi Password tidak boleh kosong!',
  'Email sudah terdaftar.': 'Email sudah terdaftar.',
  'Mohon konfirmasi privasi pengguna dan kebijakan.':
      'Mohon konfirmasi privasi pengguna dan kebijakan.',
  'Password dan Konfirmasi Password tidak sama.':
      'Password dan Konfirmasi Password tidak sama.',
  'Error': 'Error',
  'Tidak ada koneksi internet.': 'Tidak ada koneksi internet.',
};
