const Map<String, String> translationsIDID = {
  'Profile': 'Profil',
  'Sign in to continue!': 'Masuk untuk melanjutkan!',
  'Forgot password?': 'Lupa kata sandi?',
  'Login': 'Login',
  'Available Promos': 'Promo yang tersedia',
  'Password': 'Kata Sandi',
  'Email Address': 'Alamat Email',
  'Email address is required!': 'Alamat email diperlukan!',
  'Password is required!': 'Kata sandi diperlukan!',
  'or': 'atau',
  'Sign in using ': 'Masuk menggunakan ',
  'Being processed...': 'Sedang diproses...',
  'Warning': 'Peringatan',
  'Wrong Email & Password': 'Email & Kata Sandi Salah',
  'Try again': 'Try again',
  'Terms & Conditions': 'Syarat & Ketentuan',
  'Promo Name': 'Nama Promo',
  'Change': 'Ubah',
  'Verify your ID card now!': 'Verifikasi KTP mu sekarang!',
  'Account Info': 'Info Akun',
  'Name': 'Nama',
  'Birth date': 'Tanggal lahir',
  'Phone number': 'Nomor telepon',
  'Email': 'Email',
  'Change PIN': 'Ubah PIN',
  'Change language': 'Ganti bahasa',
  'Rating': 'Penilaian',
  'Rate Now': 'Nilai Sekarang',
  'Other info': 'Info lainnya',
  'Privacy & Policy': 'Privasi & Kebijakan',
  'Device Info': 'Info Perangkat',
  'Device Version': 'Versi Perangkat',
  'Log out': 'Keluar',
  'In Frame Webview': 'Tampilan Web Dalam Bingkai',
  'Total orders': 'Jumlah pesanan',
  'Order': 'Pesanan',
  'Cancel': 'Batalkan',
  'Food': 'Makanan',
  'Drink': 'Minuman',
  'success': 'sukses',
  'Discount': 'Diskon',
  'voucher': 'voucher',
  'Payment': 'Pembayaran',
  'Total payment': 'Total pembayaran',
  'In the queue': 'Dalam antrian',
  'Under preparation': 'Sedang disiapkan',
  'On delivery': 'Sedang diantar',
  'Finished': 'Selesai',
  'Canceled': 'Dibatalkan',
  'Give review': 'Berikan ulasan',
  'Order Again': 'Pesan lagi',
  'Ongoing': 'Dalam proses',
  'History': 'Riwayat',
  'Your order is being prepared': 'Pesanan Anda sedang disiapkan',
  'Order accepted': 'Pesanan diterima',
  'Please take your order': 'Silakan diambil',
  'Order completed': 'Pesanan selesai',
  'Failed!': 'Gagal!',
  'Failed': 'Gagal',
  'Fetch All Order By User Id Failed':
      'Ambil Semua Pesanan Berdasarkan ID Pengguna Gagal',
  'loading': 'memuat',
  'All status': 'Semua status',
  'all': 'semua',
  'completed': 'selesai',
  'Completed': 'Selesai',
  'canceled': 'dibatalkan',
  'Finding Your Location...': 'Mencari Lokasi Anda...',
  'Map Marker': 'Penanda Peta',
  'Open Settings': 'Buka Pengaturan',
  'Oops no internet connection.': 'Ups, tidak ada koneksi internet.',
  'Make sure wifi or cellular data is connected, then press the retry button.':
      'Pastikan wifi atau data seluler terhubung, lalu tekan tombol coba lagi.',
  'Search': 'Pencarian',
  'All Menu': 'Semua Menu',
  'Add Note': 'Tambahkan Catatan',
  'Delete': 'Hapus',
  'Fetch All Menu Failed': 'Ambil Semua Menu Gagal',
  'Fetch All Menu By Category': 'Ambil Semua Menu Berdasarkan Kategori',
  'Fetch All Promo Failed': 'Ambil Semua Promo Gagal',
  'Enter your email address to change your password':
      'Masukkan alamat email Anda untuk mengubah kata sandi Anda',
  'Input Email Address': 'Masukkan Alamat Email',
  'Email address cannot be empty': 'Alamat email tidak boleh kosong',
  'Change Password': 'Ubah Kata Sandi',
  'Enter the OTP code that has been sent to your email':
      'Masukkan kode OTP yang telah dikirim ke email Anda',
  'Wrong OTP code': 'Kode OTP salah',
  'Success': 'Sukses',
  'Valid OTP Code': 'Kode OTP Valid',
  'Price': 'Harga',
  'Level': 'Level',
  'Topping': 'Toping',
  'Note': 'Catatan',
  'Checkout': 'Checkout',
  'Menu Details': 'Detail Menu',
  'Make Notes': 'Tambahkan Catatan',
  'Input notes': 'Masukkan Catatan',
  'Home': 'Beranda',
  'Failed to fetch data': 'Gagal mengambil data',
  'Please authenticate to confirm order':
      'Harap autentikasi untuk mengonfirmasi pesanan',
  'PIN already wrong 3 times. Please try again later.':
      'PIN sudah salah 3 kali. Silakan coba lagi nanti.',
  'Select Voucher': 'Pilih Voucher',
  'Choose Topping': 'Pilih Toping',
  'Choose Level': 'Pilih Level',
  'Add To Order': 'Tambahkan ke Pesanan',
  'Choose Voucher': 'Pilih Voucher',
  'Ok': 'Oke',
  'Voucher usage cannot be combined with ':
      'Penggunaan voucher tidak dapat digabung dengan ',
  'discount employee reward program': 'discount employee reward program',
  'Info Discount': 'Info Diskon',
  'Filling Out the Survey': 'Mengisi Survey',
  'Late <3x': 'Terlambat <3x',
  'Finger Print': 'Sidik Jari',
  'Verify order': 'Verifikasi pesanan',
  'Order is being prepared': 'Pesanan sedang disiapkan',
  'Enter PIN code': 'Masukkan kode PIN',
  'Already Ordered? Track your order here.':
      'Sudah Pesan? Lacak pesananmu di sini.',
  'Start placing your order.': 'Mulai buat pesanan.',
  'The food you ordered will appear here so you can find your favorite menu again!':
      'Makanan yang kamu pesan akan muncul di sini agar kamu bisa menemukan menu favoritmu lagi!',
  'Try again later.': 'Coba lagi nanti.',
  'Save': 'Simpan',
};
