const Map<String, String> translationsEnUs = {
  'Daftar Pemesanan': 'Book List',
  'Terjadi kesalahan saat memuat pesanan!': 'Error loading book!',
  'Terjadi kesalahan saat memuat destinasi!': 'Error loading destination!',
  'Gratis': 'Free',
  'Tertunda': 'Pending',
  'Sukses': 'Success',
  'Dibatalkan': 'Canceled',
  'Konfirmasi': 'Confirmation',
  'Apakah anda ingin membatalkan pemesanan?':
      'Do you want to cancel your book?',
  'Ya': 'Yes',
  'Tidak': 'No',
  'Tunggu sebentar...': 'Wait a moment...',
  'Apakah anda ingin membayar pemesanan?':
      'Would you like to pay for your book?',
  'Data Pemesanan': 'Data Book',
  'Nama': 'Name',
  'Nomor Telpon': 'Phone number',
  'Tanggal': 'Date',
  'Waktu': 'Time',
  'Jumlah Orang': 'Number of people',
  'Total Harga': 'Total price',
  'Batalkan': 'Cancel',
  'Bayar Sekarang': 'Pay Now',
  'Konfirmasi Pemesanan': 'Order Confirmation',
  'Detail Informasi': 'Information Details',
  'Selanjutnya': 'Next',
  'Buat Pesanan': 'Place an Order',
  'Rubah Data': 'Change Data',
  'Harga': 'Price',
  'Booking maks. h-1': 'Booking maks. d-1',
  'Tanggal*': 'Date*',
  'Nama Lengkap*': 'Full Name*',
  'Masukkan Nama Lengkap': 'Enter Full Name',
  'Nama lengkap tidak boleh kosong!': 'Full name cannot be empty!',
  'Nomor Telpon*': 'Phone Number*',
  'Masukkan Nomor Telpon': 'Enter Phone Number',
  'Nomor telpon tidak boleh kosong!': 'Phone number cannot be empty!',
  'Jumlah Orang*': 'Number of people*',
  'Catatan': 'Notes',
  'Masukkan Catatan': 'Enter Notes',
  'Catatan tidak boleh kosong!': 'Notes cannot be empty!',
  'Waktu*': 'Time*',
  'Memuat...': 'Loading...',
  'Cari destinasi...': 'Search Destination...',
  'Destinasi tidak ada!': 'Destination does not exist!',
  'Terjadi kesalahan saat memuat detail destinasi!':
      'An error occurred while loading destination details!',
  'Berhasil menyimpan destinasi!': 'Successfully added destination!',
  'Yuk cari destinasi lainnya.': "Let's look for other destinations.",
  'Gagal!': 'Fail!',
  'Terjadi masalah dengan server, coba lagi nanti.':
      'There was a problem with the server, please try again later.',
  'Berhasil menghapus destinasi!': 'Successfully deleted destination!',
  'Pesan': 'Booking',
  'Deskripsi': 'Description',
  'Lokasi': 'Location',
  'Buka di maps >': 'Open on maps >',
  'Profil': 'Profile',
  'Pengaturan Akun': 'Account Settings',
  'Informasi Pribadi': 'Personal Information',
  'Bookmark': 'Bookmark',
  'Ubah Bahasa': 'Change Language',
  'Keluar': 'Log out',
  'Lainnya': 'Other',
  'Privasi & Kebijakan': 'Privacy & Policy',
  'Informasi Perangkat': 'Device Information',
  'Versi Perangkat': 'Device Version',
  'Terjadi kesalahan saat memuat bookmark!': 'Error loading bookmark!',
  'Tampilan Web Dalam Bingkai': 'In Frame Webview',
  'Apakah anda ingin menyimpan perubahan?': 'Do you want to save changes?',
  'Berhasil!': 'Succeed!',
  'Profil pengguna sudah tersimpan.': 'The user profile has been saved.',
  'Edit': 'Edit',
  'Email': 'Email',
  'Nama Pengguna': 'Username',
  'Nama pengguna tidak boleh kosong!': 'Username cannot be empty!',
  'Alamat': 'Address',
  'Ganti Foto Profil': 'Change Profile Photo',
  'Perhatian!': 'Attention!',
  'Email dan password salah.': 'Email and password are incorrect.',
  'Error, coba lagi nanti.': 'Error, please try again later.',
  'Oke': 'Ok',
  'Gagal, coba lagi nanti.': 'Failed, try again later.',
  'Petualanganmu Dimulai di Sini!': 'Your Adventure Starts Here!',
  'Lupa password?': 'Forgot the password?',
  'Masuk': 'Login',
  'Daftar dengan ': 'Sign up with ',
  'atau': 'or',
  'Alamat Email': 'Email Address',
  'Alamat email tidak boleh kosong!': 'The email address cannot be empty!',
  'Kata Sandi': 'Password',
  'Kata sandi tidak boleh kosong!': 'Password cannot be empty!',
  'Belum punya akun?': "Don't have an account yet?",
  'Daftar': 'Sign Up',
  'Siapkan akun Anda': 'Set up your account',
  'Silahkan mengisi semua informasi yang dibutuhkan untuk membuat akun baru':
      'Please fill in all the information required to create a new account.',
  'Setuju dengan ': 'Agree with ',
  'ketentuan penggunaan ': 'terms of use ',
  'dan ': 'and ',
  'kebijakan privasi': 'privacy policy',
  'Buat Akun': 'Create Account',
  'Konfirmasi Ulang Kata Sandi': 'Reconfirm Password',
  'Konfirmasi Password tidak boleh kosong!':
      'Reconfirm Password cannot be empty!',
  'Email sudah terdaftar.': 'Email already registered.',
  'Mohon konfirmasi privasi pengguna dan kebijakan.':
      'Please confirm user privacy and policies.',
  'Password dan Konfirmasi Password tidak sama.':
      'Password and Confirm Password are not the same.',
  'Error': 'Error',
  'Tidak ada koneksi internet.': 'No internet connection.',
};
