const Map<String, String> translationsEnUs = {
  'Profile': 'Profile',
  'Sign in to continue!': 'Sign in to continue!',
  'Forgot password?': 'Forgot password?',
  'Login': 'Login',
  'Available Promos': 'Available Promos',
  'Password': 'Password',
  'Email Address': 'Email Address',
  'Email address is required!': 'Email address is required!',
  'Password is required!': 'Password is required!',
  'or': 'or',
  'Sign in using ': 'Sign in using ',
  'Being processed...': 'Being processed...',
  'Warning': 'Warning',
  'Wrong Email & Password': 'Wrong Email & Password',
  'Try again': 'Try again',
  'Terms & Conditions': 'Terms & Conditions',
  'Promo Name': 'Promo Name',
  'Change': 'Change',
  'Verify your ID card now!': 'Verify your ID card now!',
  'Account Info': 'Account Info',
  'Name': 'Name',
  'Birth date': 'Birth date',
  'Phone number': 'Phone number',
  'Email': 'Email',
  'Change PIN': 'Change PIN',
  'Change language': 'Change language',
  'Rating': 'Rating',
  'Rate Now': 'Rate Now',
  'Other info': 'Other info',
  'Privacy & Policy': 'Privacy & Policy',
  'Device Info': 'Device Info',
  'Device Version': 'Device Version',
  'Log out': 'Log out',
  'In Frame Webview': 'In Frame Webview',
  'Total orders': 'Total orders',
  'Order': 'Order',
  'Cancel': 'Cancel',
  'Food': 'Food',
  'Drink': 'Drink',
  'success': 'success',
  'Discount': 'Discount',
  'voucher': 'voucher',
  'Payment': 'Payment',
  'Total payment': 'Total payment',
  'In the queue': 'In the queue',
  'Under preparation': 'Under preparation',
  'On delivery': 'On delivery',
  'Finished': 'Finished',
  'Canceled': 'Canceled',
  'Give review': 'Give review',
  'Order Again': 'Order Again',
  'Ongoing': 'Ongoing',
  'History': 'History',
  'Your order is being prepared': 'Your order is being prepared',
  'Order accepted': 'Order accepted',
  'Please take your order': 'Please take your order',
  'Order completed': 'Order completed',
  'Failed!': 'Failed!',
  'Failed': 'Failed',
  'Fetch All Order By User Id Failed': 'Fetch All Order By User Id Failed',
  'loading': 'loading',
  'All status': 'All status',
  'all': 'all',
  'completed': 'completed',
  'Completed': 'Completed',
  'canceled': 'canceled',
  'Finding Your Location...': 'Finding Your Location...',
  'Map Marker': 'Map Marker',
  'Open Settings': 'Open Settings',
  'Oops no internet connection.': 'Oops no internet connection.',
  'Make sure wifi or cellular data is connected, then press the retry button.':
      'Make sure wifi or cellular data is connected, then press the retry button.',
  'Search': 'Search',
  'All Menu': 'All Menu',
  'Add Note': 'Add Note',
  'Delete': 'Delete',
  'Fetch All Menu Failed': 'Fetch All Menu Failed',
  'Fetch All Menu By Category': 'Fetch All Menu By Category',
  'Fetch All Promo Failed': 'Fetch All Promo Failed',
  'Enter your email address to change your password':
      'Enter your email address to change your password',
  'Input Email Address': 'Input Email Address',
  'Email address cannot be empty': 'Email address cannot be empty',
  'Change Password': 'Change Password',
  'Enter the OTP code that has been sent to your email':
      'Enter the OTP code that has been sent to your email',
  'Wrong OTP code': 'Wrong OTP code',
  'Success': 'Success',
  'Valid OTP Code': 'Valid OTP Code',
  'Price': 'Price',
  'Level': 'Level',
  'Topping': 'Topping',
  'Note': 'Note',
  'Checkout': 'Checkout',
  'Menu Details': 'Menu Details',
  'Make Notes': 'Make Notes',
  'Input notes': 'Input notes',
  'Home': 'Home',
  'Failed to fetch data': 'Failed to fetch data',
  'Please authenticate to confirm order':
      'Please authenticate to confirm order',
  'PIN already wrong 3 times. Please try again later.':
      'PIN already wrong 3 times. Please try again later.',
  'Semua Menu': 'All Menu',
  'Makanan': 'Food',
  'Minuman': 'Drink',
  'Select Voucher': 'Select Voucher',
  'Choose Topping': 'Choose Topping',
  'Choose Level': 'Choose Level',
  'Add To Order': 'Add To Order',
  'Choose Voucher': 'Choose Voucher',
  'Ok': 'Ok',
  'Voucher usage cannot be combined with ':
      'Voucher usage cannot be combined with ',
  'discount employee reward program': 'discount employee reward program',
  'Info Discount': 'Info Discount',
  'Filling Out the Survey': 'Filling Out the Survey',
  'Late <3x': 'Late <3x',
  'Finger Print': 'Finger Print',
  'Verify order': 'Verify order',
  'Order is being prepared': 'Order is being prepared',
  'Enter PIN code': 'Enter PIN code',
  'Already Ordered? Track your order here.':
      'Already Ordered? Track your order here.',
  'Start placing your order.': 'Start placing your order.',
  'The food you ordered will appear here so you can find your favorite menu again!':
      'The food you ordered will appear here so you can find your favorite menu again!',
  'Try again later.': 'Try again later.',
  'Save': 'Save',
};
